import type { Product } from "@/types/legacy-product";

export const ACCESSORIES: Product[] = [
  {
    id: "ac-airpods-4",
    slug: "airpods-4",
    category: "accessories",
    brand: "Apple",
    name: "AirPods 4",
    price: 5990,
    icon: "headphones",
    inStock: true,
    shortDescription: "Компактные беспроводные наушники Apple",
    description: "AirPods 4 — лёгкие и удобные наушники с чистым звуком и быстрым подключением к устройствам Apple.",
    specs: [
      { label: "Тип", value: "Внутриканальные" },
      { label: "Автономность", value: "до 5 часов, до 30 часов с кейсом" },
      { label: "Зарядка", value: "USB-C" },
    ],
  },
  {
    id: "ac-airpods-pro-3",
    slug: "airpods-pro-3",
    category: "accessories",
    brand: "Apple",
    name: "AirPods Pro 3",
    price: 10600,
    icon: "headphones",
    badge: "Хит продаж",
    inStock: true,
    shortDescription: "Активное шумоподавление и адаптивный звук",
    description: "AirPods Pro 3 — с активным шумоподавлением, прозрачным режимом и персонализированным пространственным звуком.",
    specs: [
      { label: "Шумоподавление", value: "Активное" },
      { label: "Автономность", value: "до 6 часов, до 24 часов с кейсом" },
      { label: "Защита", value: "IP57" },
    ],
  },
  {
    id: "ac-apple-watch-se-3",
    slug: "apple-watch-se-3",
    category: "accessories",
    brand: "Apple",
    name: "Apple Watch SE 3 40 мм",
    price: 28990,
    icon: "watch",
    inStock: true,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Доступные умные часы с базовыми функциями здоровья",
    description: "Apple Watch SE 3 — отслеживание активности, сна и уведомлений по доступной цене.",
    specs: [
      { label: "Экран", value: "Retina LTPO OLED" },
      { label: "Датчики", value: "Пульс, сон, уровень кислорода" },
      { label: "Совместимость", value: "iPhone" },
    ],
  },
  {
    id: "ac-apple-watch-series-11",
    slug: "apple-watch-series-11",
    category: "accessories",
    brand: "Apple",
    name: "Apple Watch Series 11 41 мм",
    price: 44990,
    icon: "watch",
    badge: "Новинка",
    inStock: true,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Топовые умные часы с расширенным мониторингом здоровья",
    description: "Apple Watch Series 11 — самый функциональный вариант линейки: ЭКГ, температура тела, точный GPS.",
    specs: [
      { label: "Экран", value: "Always-On Retina LTPO OLED" },
      { label: "Датчики", value: "ЭКГ, температура, пульс" },
      { label: "Защита", value: "Влагозащита 50 м" },
    ],
  },
  {
    id: "ac-galaxy-watch7",
    slug: "samsung-galaxy-watch7",
    category: "accessories",
    brand: "Samsung",
    name: "Samsung Galaxy Watch7 40 мм",
    price: 24990,
    icon: "watch",
    inStock: true,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Умные часы на Wear OS с мониторингом здоровья",
    description: "Galaxy Watch7 — стильные часы с точным отслеживанием сна, тренировок и состава тела.",
    specs: [
      { label: "ОС", value: "Wear OS, One UI Watch" },
      { label: "Датчики", value: "Пульс, сон, состав тела" },
      { label: "Совместимость", value: "Android" },
    ],
  },
  {
    id: "ac-galaxy-buds3-pro",
    slug: "samsung-galaxy-buds3-pro",
    category: "accessories",
    brand: "Samsung",
    name: "Samsung Galaxy Buds3 Pro",
    price: 14990,
    icon: "headphones",
    inStock: true,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Наушники с активным шумоподавлением от Samsung",
    description: "Galaxy Buds3 Pro — премиальные наушники с чистым звуком и адаптивным шумоподавлением.",
    specs: [
      { label: "Шумоподавление", value: "Активное" },
      { label: "Автономность", value: "до 6 часов, до 26 часов с кейсом" },
      { label: "Защита", value: "IP57" },
    ],
  },
  {
    id: "ac-magsafe-case",
    slug: "chekhol-magsafe-silikon",
    category: "accessories",
    brand: "Apple",
    name: "Силиконовый чехол MagSafe",
    price: 3990,
    icon: "case",
    inStock: true,
    shortDescription: "Оригинальный силиконовый чехол с магнитным креплением",
    description: "Мягкий силиконовый чехол с внутренней подкладкой из микроволокна и магнитами MagSafe.",
    specs: [
      { label: "Материал", value: "Силикон" },
      { label: "Крепление", value: "MagSafe" },
    ],
  },
  {
    id: "ac-charger-20w",
    slug: "setevoy-adapter-20w",
    category: "accessories",
    brand: "Apple",
    name: "Сетевой адаптер питания 20 Вт",
    price: 2490,
    icon: "charger",
    inStock: true,
    shortDescription: "Компактный адаптер для быстрой зарядки",
    description: "Адаптер USB-C мощностью 20 Вт для быстрой зарядки смартфонов и наушников.",
    specs: [
      { label: "Мощность", value: "20 Вт" },
      { label: "Разъём", value: "USB-C" },
    ],
  },
];
