import type { Product } from "@/types/product";

export const DYSON: Product[] = [
  {
    id: "dy-airstrait-ht01",
    slug: "dyson-airstrait-ht01",
    category: "dyson",
    brand: "Dyson",
    name: "Dyson Airstrait HT01",
    price: 30500,
    icon: "hairdryer",
    badge: "Новинка",
    inStock: true,
    shortDescription: "Выпрямитель и сушка волос без нагревательных пластин",
    description: "Dyson Airstrait сушит и выпрямляет волосы одновременно потоком воздуха, без раскалённых пластин.",
    specs: [
      { label: "Тип", value: "Стайлер-выпрямитель" },
      { label: "Технология", value: "Airstrait, без пластин" },
    ],
  },
  {
    id: "dy-airwrap-hs08",
    slug: "dyson-airwrap-hs08",
    category: "dyson",
    brand: "Dyson",
    name: "Dyson Airwrap HS08",
    price: 36000,
    icon: "hairdryer",
    inStock: true,
    shortDescription: "Стайлер для укладки без экстремальных температур",
    description: "Dyson Airwrap HS08 — многофункциональный стайлер для завивки, разглаживания и укладки волос.",
    specs: [
      { label: "Насадки", value: "В комплекте" },
      { label: "Технология", value: "Coanda эффект" },
    ],
  },
  {
    id: "dy-airwrap-hs09",
    slug: "dyson-airwrap-hs09",
    category: "dyson",
    brand: "Dyson",
    name: "Dyson Airwrap HS09",
    price: 44000,
    icon: "hairdryer",
    badge: "Хит продаж",
    inStock: true,
    shortDescription: "Расширенный набор насадок для укладки",
    description: "Dyson Airwrap HS09 — топовая версия стайлера с полным набором насадок для любых причёсок.",
    specs: [
      { label: "Насадки", value: "Полный комплект" },
      { label: "Технология", value: "Coanda эффект" },
    ],
  },
  {
    id: "dy-v11-absolute",
    slug: "dyson-v11-absolute",
    category: "dyson",
    brand: "Dyson",
    name: "Dyson V11 Absolute",
    price: 51440,
    icon: "vacuum",
    inStock: true,
    shortDescription: "Беспроводной пылесос с интеллектуальным управлением мощностью",
    description: "Dyson V11 Absolute автоматически регулирует мощность всасывания в зависимости от типа пола.",
    specs: [
      { label: "Тип", value: "Беспроводной вертикальный" },
      { label: "Время работы", value: "до 60 минут" },
    ],
  },
  {
    id: "dy-v16-piston-animal",
    slug: "dyson-v16-piston-animal",
    category: "dyson",
    brand: "Dyson",
    name: "Dyson V16 Piston Animal",
    price: 61990,
    icon: "vacuum",
    inStock: true,
    shortDescription: "Пылесос с лазерной подсветкой пыли",
    description: "Dyson V16 Piston Animal подсвечивает микропыль лазером и показывает уровень загрязнения на экране.",
    specs: [
      { label: "Тип", value: "Беспроводной вертикальный" },
      { label: "Особенность", value: "Лазерная подсветка пыли" },
    ],
  },
  {
    id: "dy-v15-detect-absolute",
    slug: "dyson-v15-detect-absolute",
    category: "dyson",
    brand: "Dyson",
    name: "Dyson V15 Detect Absolute",
    price: 68240,
    icon: "vacuum",
    badge: "Хит продаж",
    inStock: true,
    shortDescription: "Флагманский пылесос с датчиком частиц пыли",
    description: "Dyson V15 Detect Absolute считает и показывает частицы пыли в реальном времени, автоматически подстраивая мощность.",
    specs: [
      { label: "Тип", value: "Беспроводной вертикальный" },
      { label: "Особенность", value: "Датчик частиц пыли" },
    ],
  },
];
