import type { Product } from "@/types/product";

export const SMARTPHONES: Product[] = [
  {
    id: "sp-iphone-17-128",
    slug: "iphone-17-128gb",
    category: "smartphones",
    brand: "Apple",
    name: "iPhone 17 128 ГБ",
    price: 44099,
    icon: "smartphone",
    badge: "Хит продаж",
    inStock: true,
    memoryGb: 128,
    shortDescription: "Новый iPhone 17 с чипом A19 и улучшенной камерой",
    description:
      "iPhone 17 сочетает мощный чип A19, яркий дисплей Super Retina XDR и улучшенную систему камер. Оптимальный выбор для повседневных задач.",
    specs: [
      { label: "Экран", value: "6.3\" Super Retina XDR" },
      { label: "Чип", value: "Apple A19" },
      { label: "Память", value: "128 ГБ" },
      { label: "Камера", value: "48 + 12 Мп" },
    ],
  },
  {
    id: "sp-iphone-17-256",
    slug: "iphone-17-256gb",
    category: "smartphones",
    brand: "Apple",
    name: "iPhone 17 256 ГБ",
    price: 50990,
    icon: "smartphone",
    inStock: true,
    memoryGb: 256,
    shortDescription: "iPhone 17 с увеличенным объёмом памяти",
    description:
      "Та же производительность iPhone 17, но с запасом памяти на фото, видео и приложения.",
    specs: [
      { label: "Экран", value: "6.3\" Super Retina XDR" },
      { label: "Чип", value: "Apple A19" },
      { label: "Память", value: "256 ГБ" },
      { label: "Камера", value: "48 + 12 Мп" },
    ],
  },
  {
    id: "sp-iphone-17-pro-256",
    slug: "iphone-17-pro-256gb",
    category: "smartphones",
    brand: "Apple",
    name: "iPhone 17 Pro 256 ГБ",
    price: 95490,
    icon: "smartphone",
    inStock: true,
    memoryGb: 256,
    shortDescription: "Титановый корпус, тройная камера, чип A19 Pro",
    description:
      "iPhone 17 Pro — флагманская линейка с титановым корпусом, профессиональной тройной камерой и самым быстрым чипом Apple.",
    specs: [
      { label: "Экран", value: "6.3\" ProMotion 120 Гц" },
      { label: "Чип", value: "Apple A19 Pro" },
      { label: "Память", value: "256 ГБ" },
      { label: "Камера", value: "48 + 48 + 12 Мп" },
    ],
  },
  {
    id: "sp-iphone-17-pro-512",
    slug: "iphone-17-pro-512gb",
    category: "smartphones",
    brand: "Apple",
    name: "iPhone 17 Pro 512 ГБ",
    price: 107990,
    icon: "smartphone",
    badge: "Новинка",
    inStock: true,
    memoryGb: 512,
    shortDescription: "Максимальная память для профессиональной съёмки",
    description:
      "Топовая версия iPhone 17 Pro с 512 ГБ памяти — для тех, кто снимает видео в ProRes и хранит большие библиотеки.",
    specs: [
      { label: "Экран", value: "6.3\" ProMotion 120 Гц" },
      { label: "Чип", value: "Apple A19 Pro" },
      { label: "Память", value: "512 ГБ" },
      { label: "Камера", value: "48 + 48 + 12 Мп" },
    ],
  },
  {
    id: "sp-galaxy-s26-128",
    slug: "samsung-galaxy-s26-128gb",
    category: "smartphones",
    brand: "Samsung",
    name: "Samsung Galaxy S26 128 ГБ",
    price: 64990,
    icon: "smartphone",
    inStock: true,
    memoryGb: 128,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Флагман Samsung с AI-функциями и ярким AMOLED",
    description:
      "Galaxy S26 — производительный флагман с динамическим AMOLED-дисплеем, мощной камерой и функциями Galaxy AI.",
    specs: [
      { label: "Экран", value: "6.2\" Dynamic AMOLED 2X" },
      { label: "Память", value: "128 ГБ" },
      { label: "Камера", value: "50 + 12 + 10 Мп" },
      { label: "Батарея", value: "4000 мА·ч" },
    ],
  },
  {
    id: "sp-galaxy-s26-ultra-256",
    slug: "samsung-galaxy-s26-ultra-256gb",
    category: "smartphones",
    brand: "Samsung",
    name: "Samsung Galaxy S26 Ultra 256 ГБ",
    price: 114990,
    icon: "smartphone",
    badge: "Хит продаж",
    inStock: true,
    memoryGb: 256,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Топовая камера, S Pen и самый большой экран линейки",
    description:
      "Galaxy S26 Ultra — вершина линейки Samsung: профессиональная камера, встроенный S Pen и максимальная производительность.",
    specs: [
      { label: "Экран", value: "6.9\" Dynamic AMOLED 2X" },
      { label: "Память", value: "256 ГБ" },
      { label: "Камера", value: "200 + 50 + 10 + 10 Мп" },
      { label: "Стилус", value: "S Pen в комплекте" },
    ],
  },
  {
    id: "sp-galaxy-z-fold7-256",
    slug: "samsung-galaxy-z-fold7-256gb",
    category: "smartphones",
    brand: "Samsung",
    name: "Samsung Galaxy Z Fold7 256 ГБ",
    price: 189990,
    icon: "smartphone",
    badge: "Новинка",
    inStock: false,
    memoryGb: 256,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Складной смартфон с большим внутренним экраном",
    description:
      "Galaxy Z Fold7 раскладывается в полноценный планшет — для многозадачности и работы с приложениями бок о бок.",
    specs: [
      { label: "Внешний экран", value: "6.3\"" },
      { label: "Внутренний экран", value: "8.0\" разворачивается" },
      { label: "Память", value: "256 ГБ" },
      { label: "Особенность", value: "Складная конструкция" },
    ],
  },
  {
    id: "sp-galaxy-z-flip7-256",
    slug: "samsung-galaxy-z-flip7-256gb",
    category: "smartphones",
    brand: "Samsung",
    name: "Samsung Galaxy Z Flip7 256 ГБ",
    price: 124990,
    icon: "smartphone",
    inStock: true,
    memoryGb: 256,
    // оценочно, рыночный ориентир 2026
    shortDescription: "Компактный складной смартфон-раскладушка",
    description:
      "Galaxy Z Flip7 складывается пополам и умещается в любом кармане, не теряя во флагманских характеристиках.",
    specs: [
      { label: "Экран", value: "6.7\" разворачивается" },
      { label: "Внешний дисплей", value: "3.4\"" },
      { label: "Память", value: "256 ГБ" },
      { label: "Особенность", value: "Компактный форм-фактор" },
    ],
  },
];
