'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,PenLine,ScanSearch,ShieldCheck,Sparkles} from 'lucide-react';
import {Viewer} from './viewer';
import {HeroMedia} from './hero-media';
import styles from './page.module.css';
const productHref='/product/galaxy-s26-ultra';
const stories=[{title:'Найдите. Просто обведите.',body:'Circle to Search помогает искать то, что привлекло ваше внимание, прямо на экране.',icon:ScanSearch},{title:'Опишите. И измените.',body:'Photo Assist помогает редактировать фотографии с помощью слов. От идеи до нового кадра — в привычной Галерее.',icon:Sparkles},{title:'Ваш день. Уже перед вами.',body:'Now Brief собирает персональные подсказки и напоминания, чтобы важное оставалось под рукой.',icon:Check}];
export function GalaxyPage(){const root=useRef<HTMLDivElement>(null);const [ai,setAi]=useState(0);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:.35,transform:'translateY(32px)'},{opacity:1,transform:'translateY(0)'}],{duration:850,easing:'cubic-bezier(.2,.7,.2,1)'});observer.unobserve(e.target);}}),{threshold:.12});root.current?.querySelectorAll('[data-reveal]').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);const ActiveIcon=stories[ai].icon;
 return <div ref={root} className={styles.page}>
 <HeroMedia/>
 <header className={styles.hero}><p className={styles.kicker}>Samsung Galaxy S26 Ultra</p><h1>Больше, чем<br/>вы представляли.</h1><p className={styles.intro}>Пространство для ваших идей.<br/>И возможностей, которые всегда с вами.</p><div className={styles.heroAction}><Link className={styles.buy} href={productHref}>Выбрать свой Galaxy <ArrowUpRight size={18}/></Link></div><div className={styles.heroVisual}><Image src="/media/galaxy-s26-ultra/photos/hero-photo.webp" alt="Серебристый Galaxy S26 Ultra: корпус, экран и S Pen на белом фоне" fill sizes="(max-width: 760px) 100vw, 960px"/></div><p className={styles.heroCaption}>Galaxy AI. Новые возможности начинаются с вас.</p></header>
 <section className={styles.overview} aria-label="Возможности Galaxy"><div><span>200 Мп</span><p>Детали, которые хочется сохранить.</p></div><div><span>6,9″</span><p>Большой экран для больших идей.</p></div><div><span>S Pen</span><p>Точность в каждом движении.</p></div></section>
 <section id="design" className={styles.section}><div className={styles.heading} data-reveal><p>Дизайн</p><h2>Рассмотрите ближе.<br/>С любой стороны.</h2><p className={styles.description}>Чистые линии. Плавные грани. Выберите оттенок и поверните Galaxy так, как повернули бы его в руках.</p></div><Viewer/></section>
 <section id="camera" className={styles.section}><div className={styles.heading} data-reveal><p>Камера</p><h2>В кадре — всё,<br/>что вы почувствовали.</h2></div><div className={styles.cameraCard} data-reveal><div><h3>200 миллионов<br/>причин приблизить.</h3><p>Основная камера 200 Мп сохраняет мелкие детали. Более широкая диафрагма помогает снимать при слабом освещении, а Nightography Video — передавать настроение вечера.</p></div><div className={styles.cameraVisual}><Image src="/media/galaxy-s26-ultra/photos/camera-photo.webp" alt="Крупный план камер Galaxy S26 Ultra" fill sizes="(max-width: 700px) 100vw, 650px"/></div></div></section>
 <section className={`${styles.section} ${styles.duo}`}><article className={styles.penCard} data-reveal><PenLine size={30}/><h2>Мысль появилась.<br/>Сохраните её.</h2><p>S Pen — для набросков, заметок и точных штрихов. Ваш привычный жест становится частью цифрового мира.</p><div className={styles.detailPhoto}><Image src="/media/galaxy-s26-ultra/photos/spen-photo.webp" alt="Рука рисует архитектурный эскиз стилусом S Pen на Galaxy" fill sizes="(max-width: 760px) 100vw, 580px"/></div></article><article className={styles.privacyCard} data-reveal><ShieldCheck size={30}/><h2>Ваш экран.<br/>Только для вас.</h2><p>Privacy Display ограничивает видимость под боковыми углами. Личные сообщения остаются личными — даже когда вокруг люди.</p><div className={styles.detailPhoto}><Image src="/media/galaxy-s26-ultra/photos/display-photo.webp" alt="Galaxy в руках: личная переписка в светлом кафе" fill sizes="(max-width: 760px) 100vw, 580px"/></div></article></section>
 <section id="intelligence" className={`${styles.section} ${styles.ai}`}><div className={styles.heading} data-reveal><p>Galaxy AI</p><h2>Меньше действий.<br/>Больше возможностей.</h2></div><div className={styles.aiStage}><div className={styles.aiPhoto}><Image key={ai} src={`/media/galaxy-s26-ultra/photos/${['ai-search-photo','ai-edit-photo','ai-day-photo'][ai]}.webp`} alt={['Поиск предмета по изображению на экране Galaxy','Редактирование фотографии рисовых террас Бали на Galaxy','Утренние персональные подсказки на экране Galaxy'][ai]} fill sizes="(max-width: 760px) 100vw, 700px"/></div><div><div className={styles.tabs} role="tablist" aria-label="Возможности Galaxy AI">{['Поиск','Фото','Ваш день'].map((n,i)=><button role="tab" id={`ai-tab-${i}`} aria-selected={ai===i} aria-controls="ai-panel" key={n} onClick={()=>setAi(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:2))%3;setAi(next);document.getElementById(`ai-tab-${next}`)?.focus();}}} tabIndex={ai===i?0:-1}>{n}</button>)}</div><div role="tabpanel" id="ai-panel" aria-labelledby={`ai-tab-${ai}`} className={styles.aiCopy}><ActiveIcon size={28}/><h3>{stories[ai].title}</h3><p>{stories[ai].body}</p></div></div></div></section>
 <section className={`${styles.section} ${styles.performance}`} data-reveal><p>Производительность</p><h2>Задумано много.<br/>Предусмотрено всё.</h2><div className={styles.performancePhoto}><Image src="/media/galaxy-s26-ultra/photos/performance-photo.webp" alt="Гоночная игра на Galaxy S26 Ultra в руках" fill sizes="(max-width: 760px) 100vw, 1200px"/></div><p className={styles.description}>Snapdragon 8 Elite Gen 5 for Galaxy — для игр, творчества и повседневной многозадачности. Обновлённая система охлаждения помогает сохранять стабильную работу под нагрузкой.</p></section>
 <section className={`${styles.section} ${styles.faq}`}><h2>Перед знакомством.</h2>{[{q:'Можно рассмотреть телефон вживую?',a:'Свяжитесь с Di-SMART: поможем уточнить наличие, доступные цвета и возможность знакомства с устройством.'},{q:'Как узнать цену и объём памяти?',a:'Актуальные конфигурации и стоимость уточняйте у консультанта. На этой странице показана презентация устройства.'},{q:'Galaxy AI работает на русском?',a:'Доступность языков и отдельных функций зависит от региона, приложения и версии программного обеспечения. Некоторые возможности требуют интернета и учётной записи.'}].map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</section>
 <section className={styles.closing}><p>Samsung Galaxy S26 Ultra</p><h2>Ваш следующий Galaxy.</h2><Link className={styles.buy} href={productHref}>Выбрать свой Galaxy <ArrowUpRight size={18}/></Link><Link href="/trade-in">Обменять свой смартфон по Trade-in</Link></section>
 <footer className={styles.footnote}><p>Изображения созданы с помощью ИИ для иллюстрации устройства и сценариев использования. Это не реальные снимки, сделанные камерой Galaxy. Оттенки и интерфейсы могут отличаться от устройства.</p><p>Характеристики и возможности: <a href="https://www.samsung.com/uk/smartphones/galaxy-s26-ultra/">Samsung Galaxy S26 Ultra</a>. Доступность Galaxy AI зависит от региона и условий сервиса.</p></footer>
 </div>;
}
